librium/views/main.py
from flask import Blueprint, redirect, render_template, request, url_for
from marshmallow import Schema, fields
from webargs.flaskparser import use_args

from librium.views.views import (
    get_authors,
    get_books,
    get_genres,
    get_series,
    get_years,
)

bp = Blueprint("main", __name__)


class UserArgs(Schema):
    page = fields.Integer()
    start = fields.String(required=False)
    read = fields.Boolean()
    id = fields.Integer()
    name = fields.String()
    search = fields.String()
    sort_by = fields.String()
    sort_order = fields.String(load_default="asc")


@bp.route("/")
@use_args(UserArgs, location="query")
def index(_args):
    def url_for_self(target, **args):
        return url_for(target, **dict(request.args, **args))

    return redirect(url_for_self("main.books"))


@bp.route("/a")
@use_args(UserArgs, location="query")
def authors(args):
    return render_template("main/index.html", **get_authors(args))


@bp.route("/s")
@use_args(UserArgs, location="query")
def series(args):
    return render_template("main/index.html", **get_series(args))


@bp.route("/b")
@use_args(UserArgs, location="query")
def books(args):
    return render_template("main/index.html", **get_books(args))


@bp.route("/y")
@use_args({"page": fields.Integer(), "year": fields.Integer()}, location="query")
def years(args):
    return render_template("main/index.html", **get_years(args))


@bp.route("/g")
@use_args(UserArgs, location="query")
def genres(args):
    return render_template("main/index.html", **get_genres(args))


@bp.route("/statistics")
def statistics():
    from librium.services import BookService

    stats = BookService.get_statistics()
    return render_template("main/statistics.html", **stats)


@bp.route("/problems")
def problems():
    from librium.services import BookService

    problems = BookService.get_problems()
    return render_template("main/problems.html", **problems)

librium/templates/main/body.html
{% from "main/definitions.html" import make_author_content, make_series_content, make_book_content, make_year_content, make_genre_content, make_head, make_content %}

<div class="ui fluid styled accordion">
    {% if request.args.read is defined %}
        {% set read_only = request.args.read == "true" %}
    {% endif %}
    {% if authors is defined %}
        {% set active = authors|length == 1 %}
        {% for a in authors %}
            {% set title %}
            <div class="ui stackable grid">
                <div class="fourteen wide column"><i class="dropdown icon"></i>{{ a.author }}</div>
                <div class="two wide column">
                    <div class="ui teal horizontal label">{{ a.books|length }} book{{ "s" if a.books|length > 1 }}</div>
                </div>
            </div>
            {% endset %}
            {{ make_head(a.author, a.books, active, extra=True) }}
            {% call make_content(active) %}
                {% for series in a.series %}
                    {% if (request.args.read is undefined) or (read_only and series.status.read > 0) or (read_only or series.status.unread > 0) %}
                        <div class="ui raised segment">
                            {{ make_author_content(series, [request.args.read, read_only]) }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endcall %}
        {% endfor %}
    {% elif series is defined %}
        {% set active = series|length == 1 %}
        {% for s, books in series.items() %}
            {{ make_head(s, books, active, extra=True) }}
            {% call make_content(active) %}
                {{ make_series_content(books) }}
            {% endcall %}
        {% endfor %}
    {% elif books is defined %}
        {% set active = books|length == 1 %}
        {% for b in books %}
            {{ make_head(b.title, b.read, active) }}
            {% call make_content(active) %}
                {{ make_book_content(b) }}
            {% endcall %}
        {% endfor %}
    {% elif years is defined %}
        {% set active = years|length == 1 %}
        {% for year, books in years.items() %}
            {{ make_head(year, books, active, extra=True) }}
            {% call make_content(active) %}
                {{ make_year_content(year, books) }}
            {% endcall %}
        {% endfor %}
    {% elif genres is defined %}
        {% set active = genres|length == 1 %}
        {% for gr, books in genres.items() %}
            {{ make_head(gr, books, active, extra=True) }}
            {% call make_content(active) %}
                {{ make_genre_content(books) }}
            {% endcall %}
        {% endfor %}
    {% endif %}
</div>

librium/templates/main/definitions.html
{% macro label(colour, value) %}
    <span class="ui {{ colour }} label">{{ value }}</span>
{% endmacro %}

{% macro make_author(name) %}
    <div>
        <i class="small user icon"></i>
        <a href="{{ url_for("main.authors", name=name) }}" data-content="Show all books by {{ name }}">
            {{ name }}
        </a>
    </div>
{% endmacro %}
{% macro make_series(title) %}
    <a href="{{ url_for("main.series", name=title) }}" data-content="Show all books in {{ title }}">{{ title }}</a>
{% endmacro %}
{% macro make_year(year) %}
    <a href="{{ url_for("main.year", year=year) }}" data-content="Show all books released in {{ year }}">{{ year }}</a>
{% endmacro %}
{% macro fix_index(idx, circular) -%}
    {% if circular %}
        {% set class = "horizontal blue circular" %}
    {% else %}
        {% set class = "horizontal blue" %}
    {% endif %}
    {% if idx is defined() and idx != -1 %}
        {% if idx|int == idx %}
            {% set idx = idx|int %}
        {% else %}
            {% set idx = idx * 10 %}
            {% set idx = idx|int %}
            {% set idx = idx / 10 %}
        {% endif %}
        {% if idx != 0 %}
            {{ label(class, idx) }}
        {% endif %}
    {% endif %}
{%- endmacro %}
{% macro make_index(idx, circular=True) %}
    {% if idx is sequence() %}
        {% for index in idx %}
            {{ fix_index(index, circular) }}
        {% endfor %}
    {% else %}
        {{ fix_index(idx, circular) }}
    {% endif %}
{% endmacro %}

{% macro make_book_cover(book) %}
    <a href="{{ url_for("book.index", id=book.id) }}">
        <img class="ui bordered fluid image" src="{{ url_for("covers.static", filename=book.uuid + ".jpg") }}"
             alt="{{ book.title }} cover">
    </a>
{% endmacro %}

{% macro make_sorter(sort, text, active) %}
    {% set dir = "up" if not active or request.args.sort_order == "asc" else "down" %}
    {% set asc = "asc" if not active or request.args.sort_order == "desc" else "desc" %}
    <a href="{{ url_for_self(sort_by=sort, sort_order=asc) }}" class="{% if active %}active {% endif %}item">
        {{ text }}
        <i class="sort alphabet {{ dir }} icon"></i>
    </a>
{% endmacro %}

{% macro make_author_book(book) %}
    <tr>
        <td class="two wide">
            {{ make_book_cover(book) }}
        </td>
        <td class="eight wide">
            <a href="{{ url_for("book.index", id=book.id) }}">{{ book.book }}</a>
        </td>
        <td class="two wide center aligned">
            {{ book.year }}
        </td>
        <td class="three wide center aligned">
            {{ make_index(book.idx) }}
        </td>
        <td class="one wide center aligned">
            <i class="{{ "green check" if book.read else "red times" }} icon"></i>
        </td>
    </tr>
{% endmacro %}
{% macro make_author_content(series, read) %}
    {% if series.series != "0" %}
        <div class="ui medium header">
            {{ make_series(series.series) }}
        </div>
    {% endif %}
    <table class="ui stackable structured table">
        <thead>
        <tr>
            <th class="one wide"></th>
            <th>Title</th>
            <th class="center aligned">Published</th>
            <th class="center aligned">
                {% if series.series != "0" %}
                    Index
                {% endif %}
            </th>
            <th class="center aligned">Read</th>
        </tr>
        </thead>
        <tbody>
        {% for book in series.books %}
            {{ make_author_book(book) if read[0] is undefined or book.read == read[1] }}
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro make_series_content(books) %}
    <table class="ui stackable structured table">
        <thead>
        <tr>
            <th class="two wide"></th>
            <th class="right aligned one wide">Index</th>
            <th class="six wide">Title</th>
            <th class="six wide">Authors</th>
            <th class="one wide center aligned">Published</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>
                    {{ make_book_cover(book) }}
                </td>
                <td class="right aligned">
                    {{ make_index(book.idx) }}
                </td>
                <td>
                    <a href="{{ url_for("book.index", id=book.id) }}">{{ book.name }}</a>
                </td>
                <td>
                    {% for author in book.authors %}
                        {{ make_author(author.name) }}
                    {% endfor %}
                </td>
                <td class="center aligned">{{ book.published }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro make_book_content(book) %}
    <div class="ui stackable grid">
        <div class="four wide column">
            {{ make_book_cover(book) }}
        </div>
        <div class="twelve wide column">
            <table class="ui stackable structured table">
                <thead>
                <tr>
                    <th class="two wide center aligned">Released</th>
                    <th class="four wide">Authors</th>
                    <th colspan="2" class="center aligned">Series</th>
                    <th class="two wide">Link</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="center aligned two wide">
                        {{ book.released }}
                    </td>
                    <td class="six wide">
                        {% for author in book.authors %}
                            {{ make_author(author.author.name) }}
                        {% endfor %}
                    </td>
                    <td class="four wide">
                        {% for series in book.series %}
                            <div class="right aligned">{{ make_series(series.series.name) }}</div>
                        {% endfor %}
                    </td>
                    <td class="one wide">
                        {% for series in book.series %}
                            <div>{{ make_index(series.index, False) }}</div>
                        {% endfor %}
                    </td>
                    <td class="two wide">
                        <a href="{{ url_for("book.index", id=book.id) }}">
                            Link
                            <i class="small fitted linkify icon"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endmacro %}

{% macro make_year_content(year, books) %}
    <table class="ui stackable structured table">
        <thead>
        <tr>
            <th class="two wide"></th>
            <th class="four wide">Title</th>
            <th class="four wide">Authors</th>
            <th class="five wide">Series</th>
            <th class="center aligned one wide">Index</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>
                    {{ make_book_cover(book) }}
                </td>
                <td><a href="{{ url_for("book.index", id=book.id) }}">{{ book.name }}</a></td>
                <td>{% for author in book.authors %}{{ make_author(author.author.name) }}{% endfor %}</td>
                <td>
                    {% for series in book.series %}
                        <div>{{ make_series(series.series.name) }}</div>
                    {% endfor %}
                </td>
                <td class="center aligned">
                    {% for series in book.series %}
                        <div>{{ make_index(series.index, False) }}</div>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro make_genre_content(books) %}
    <table class="ui stackable structured table">
        <thead>
        <tr>
            <th class="two wide"></th>
            <th class="five wide">Title</th>
            <th class="four wide">Series</th>
            <th class="five wide">Authors</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>
                    {{ make_book_cover(book) }}
                </td>
                <td>
                    <a href="{{ url_for("book.index", id=book.id) }}">{{ book.name }}</a>
                </td>
                <td>
                    {% for series in book["series"] %}
                        <div class="ui row">
                            {% if series["idx"] %}
                                {{ make_index(series["idx"]) }}
                            {% endif %}
                            {{ make_series(series["name"]) }}
                        </div>
                    {% endfor %}
                <td>
                    {% for author in book["authors"] %}
                        {{ make_author(author["name"]) }}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endmacro %}

{% macro make_head(title, count, active, extra=False) %}
    {% if extra %}
        {% if count|length > 1 %}
            {% set e = " books" %}
        {% else %}
            {% set e = " book" %}
        {% endif %}
    {% else %}
        {% set e = "" %}
    {% endif %}
    <div class="{{ "active " if active }}title" role="button" aria-expanded="{{ "true" if active else "false" }}"
         tabindex="0">
        <div class="ui horizontal basic segments">
            <div class="ui seamless left attached basic vertically fitted compact segment">{{ title }}</div>
            <div class="ui seamless right attached right aligned basic vertically fitted compact segment">
                {% if count != True and count != False %}
                    <div class="ui red horizontal label">{{ count|length }}{{ e }}</div>
                {% else %}
                    <i class="{{ "green check" if count else "red times" }} icon"></i>
                {% endif %}
            </div>
        </div>
    </div>
{% endmacro %}

{% macro make_content(active) %}
    <div class="{{ "active" if active }} content" role="region" aria-hidden="{{ "false" if active else "true" }}">
        <div class="ui raised segment">
            {{ caller() }}
        </div>
    </div>
{% endmacro %}

{% macro favicon_for_debug(filename, ext) -%}
    img/
    {%- if config["DEBUG"] -%}
        {{ filename }}-dev
    {%- else -%}
        {{ filename }}
    {%- endif -%}
    .{{ ext }}
{%- endmacro %}

librium/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
    <div class="ui main container">
        <div class="ui section">
            {% include "main/body.html" %}
        </div>
    </div>
    {% if pagination > 1 %}
        {% include "main/pagination.html" %}
    {% endif %}
{% endblock %}

librium/templates/main/pagination.html
<div class="ui center aligned container">
    <div class="ui pagination menu">
        {% set current_page = request.args.page|int if "page" in request.args.keys() else 1 %}
        {% if current_page == 1 %}
            {% set prev_class = "disabled item" %}
            {% set prev_url = "#" %}
        {% else %}
            {% set prev_class = "item" %}
            {% set prev_url = url_for_self(page=current_page - 1) %}
        {% endif %}
        {% if current_page == pagination %}
            {% set next_class = "disabled item" %}
            {% set next_url = "#" %}
        {% else %}
            {% set next_class = "item" %}
            {% set next_url = url_for_self(page=current_page + 1) %}
        {% endif %}
        {% set offset = 3 %}
        {% if current_page <= 5 %}
            {% set offset = offset + (5 - current_page) %}
        {% elif current_page >= pagination - 5 %}
            {% set offset = offset + (pagination - 5 - current_page) %}
        {% endif %}
        <a href="{{ url_for_self(page=None) }}" class="{{ prev_class }}"><i class="angle double left icon"></i></a>
        <a href="{{ prev_url }}" class="{{ prev_class }}"><i class="angle left icon"></i></a>
        {% for x in range(1, pagination + 1) %}
            {% if (loop.first or loop.last or current_page - offset < x < current_page + offset) %}
                {% set p_class = "active item" if x == current_page else "item" %}
                <a class="{{ p_class }}" href="{{ url_for_self(page = x) }}">{{ x }}</a>
            {% elif x == current_page - offset or x == current_page + offset %}
                <div class="disabled item">&hellip;</div>
            {% endif %}
        {% endfor %}
        <a href="{{ next_url }}" class="{{ next_class }}"><i class="angle right icon"></i></a>
        <a href="{{ url_for_self(page = pagination) }}" class="{{ next_class }}"><i class="angle double right icon"></i></a>
    </div>
</div>

librium/templates/main/problems.html
{% extends 'base.html' %}
{% from "main/definitions.html" import make_head, make_content, make_book_content %}

{% block title %}Books with Problems{% endblock %}

{% block content %}
    <div class="ui main container">
        <div class="ui fluid styled segment">
            <h1 class="ui header">Books with Problems</h1>
        </div>

    <div class="ui hidden divider"></div>

        <div class="ui fluid styled accordion">
            {% for (title, contents) in [("a cover image", missing_cover), ("an ISBN", missing_isbn), ("an author", missing_author), ("a publisher", missing_publisher), ("a language", missing_language), ("a genre", missing_genre)] %}
                {% if contents|length > 0 %}
                    {{ make_head("Books missing " ~ title, contents, False, extra=True) }}
                    {% call make_content(False) %}
                        {% for b in contents %}
                            {{ make_book_content(b) }}
                            {% if not loop.last %}
                                <div class="ui divider"></div>{% endif %}
                        {% endfor %}
                    {% endcall %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

librium/templates/main/statistics.html
{% extends 'base.html' %}

{% block title %}Statistics{% endblock %}

{% block content %}
    <div class="ui main container">
        <div class="ui styled fluid segment">
            <h1 class="ui header">
                <i class="chart bar icon"></i>
                <span class="content">
                    Collection Statistics
                    <span class="ui sub header">Insights into your library</span>
                </span>
            </h1>
            <div class="ui three statistics">
                <div class="statistic">
                    <div class="value">
                        {{ _total_books }}
                    </div>
                    <div class="label">
                        Total Books
                    </div>
                </div>
                <div class="statistic">
                    <div class="value">
                        {{ _read_books }}
                    </div>
                    <div class="label">
                        Read
                    </div>
                </div>
                <div class="statistic">
                    <div class="value">
                        {% if _total_books > 0 %}
                            {{ (_read_books / _total_books * 100)|round(1) }}%
                        {% else %}
                            0%
                        {% endif %}
                    </div>
                    <div class="label">
                        Completion
                    </div>
                </div>
            </div>
            <div class="ui one statistics">
                <div class="statistic">
                    <div class="value" id="total-value-stat">
                        {{ total_price|round(2) }}
                    </div>
                    <div class="label">
                        Total Value
                    </div>
                </div>
            </div>
        </div>

        <div class="ui divider"></div>

        <div class="ui stackable grid">
            <div class="eight wide column">
                <div class="ui segment">
                    <h3 class="ui header">Read vs Unread</h3>
                    <canvas id="readStatusChart"></canvas>
                </div>
            </div>
            <div class="eight wide column">
                <div class="ui segment">
                    <h3 class="ui header">Books per Format</h3>
                    <canvas id="formatChart"></canvas>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="ui segment">
                    <h3 class="ui header">Books per Genre</h3>
                    <canvas id="genreChart"></canvas>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="ui segment">
                    <h3 class="ui header">Books per Year</h3>
                    <canvas id="yearChart"></canvas>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="ui segment">
                    <h3 class="ui header">Total Price per Year</h3>
                    <canvas id="priceYearChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const isDarkMode = document.body.classList.contains('dark-mode');
            const textColor = isDarkMode ? '#e0e0e0' : '#666';
            const gridColor = isDarkMode ? '#444' : '#eee';

            Chart.defaults.color = textColor;

            // Initialize Semantic UI components
            $('.ui.dropdown').dropdown();
            $('.ui.checkbox').checkbox();

            // Read Status Chart
            new Chart(document.getElementById('readStatusChart'), {
                type: 'doughnut',
                data: {
                    labels: ['Read', 'Unread'],
                    datasets: [{
                        data: [{{ _read_books }}, {{ _unread_books }}],
                        backgroundColor: ['#21ba45', '#db2828'],
                        borderWidth: 0
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'bottom'
                        }
                    }
                }
            });

            // Format Chart
            const formatData = {{ books_per_format|tojson }};
            new Chart(document.getElementById('formatChart'), {
                type: 'pie',
                data: {
                    labels: Object.keys(formatData),
                    datasets: [{
                        data: Object.values(formatData),
                        backgroundColor: [
                            '#2185d0', '#6435c9', '#a333c8', '#e03997', '#f2711c', '#fbbd08', '#b5cc18', '#00b5ad'
                        ],
                        borderWidth: 0
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'bottom'
                        }
                    }
                }
            });

            // Genre Chart
            const genreData = {{ books_per_genre|tojson }};
            const sortedGenres = Object.entries(genreData).sort((a, b) => b[1] - a[1]);
            new Chart(document.getElementById('genreChart'), {
                type: 'bar',
                data: {
                    labels: sortedGenres.map(x => x[0]),
                    datasets: [{
                        label: 'Books',
                        data: sortedGenres.map(x => x[1]),
                        backgroundColor: '#2185d0'
                    }]
                },
                options: {
                    responsive: true,
                    scales: {
                        x: {
                            grid: { display: false },
                            ticks: {
                                autoSkip: false
                            }
                        },
                        y: {
                            beginAtZero: true,
                            grid: { color: gridColor }
                        }
                    }
                }
            });

            // Year Chart
            const yearData = {{ books_per_year|tojson }};
            new Chart(document.getElementById('yearChart'), {
                type: 'line',
                data: {
                    labels: Object.keys(yearData),
                    datasets: [{
                        label: 'Books Released',
                        data: Object.values(yearData),
                        borderColor: '#2185d0',
                        backgroundColor: 'rgba(33, 133, 208, 0.1)',
                        fill: true,
                        tension: 0.3
                    }]
                },
                options: {
                    responsive: true,
                    scales: {
                        x: {
                            grid: {display: false}
                        },
                        y: {
                            beginAtZero: true,
                            grid: {color: gridColor},
                            ticks: {stepSize: 1}
                        }
                    }
                }
            });

            // Initialise Semantic UI components
            // Note: Basic initialization is handled by core JS, but we re-initialise
            // to ensure handlers are attached to these specific elements in the sidebar.
            $('#inflation-toggle').checkbox();

            // Currency and Inflation Logic
            const inflationFactors = {{ inflation_factors|tojson }};
            const rawPriceData = {{ price_per_year|tojson }};
            const rawTotalTotal = {{ total_price }};

            const getInflationFactor = (year, currency) => {
                const factors = inflationFactors[currency] || {};
                return factors[year] || 1.0;
            };

            const currencyInfo = document.getElementById('currency-select-value');
            const inflationToggleContainer = document.getElementById('inflation-toggle');
            const inflationToggle = inflationToggleContainer ? inflationToggleContainer.querySelector('input') : null;
            const totalValueStat = document.getElementById('total-value-stat');

            const getFormattedValue = (value) => {
                const symbol = currencyInfo ? currencyInfo.getAttribute('data-symbol') : '$';
                return `${symbol}${value.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}`;
            };

            const updatePriceChart = () => {
                if (!currencyInfo || !priceYearChart) return;

                const currency = currencyInfo.value;
                const adjustInflation = inflationToggle ? inflationToggle.checked : false;

                const labels = Object.keys(rawPriceData);
                const data = labels.map(year => {
                    let price = rawPriceData[year];
                    if (adjustInflation) {
                        price *= getInflationFactor(parseInt(year), currency);
                    }
                    return price;
                });

                priceYearChart.data.labels = labels;
                priceYearChart.data.datasets[0].data = data;
                priceYearChart.data.datasets[0].label = `Total Price (${currency}${adjustInflation ? ' Adjusted' : ''})`;
                priceYearChart.update();

                // Update total value stat
                let totalAdjusted = 0;
                let priceWithYear = 0;
                Object.keys(rawPriceData).forEach(year => {
                   let p = rawPriceData[year];
                   priceWithYear += p;
                   if (adjustInflation) p *= getInflationFactor(parseInt(year), currency);
                   totalAdjusted += p;
                });
                
                const priceWithoutYear = rawTotalTotal - priceWithYear;
                totalAdjusted += priceWithoutYear;

                if (totalValueStat) {
                    totalValueStat.innerText = getFormattedValue(totalAdjusted);
                }
            };

            if (inflationToggle) {
                inflationToggle.addEventListener('change', updatePriceChart);
            }

            const priceYearChart = new Chart(document.getElementById('priceYearChart'), {
                type: 'line',
                data: {
                    labels: [],
                    datasets: [{
                        label: 'Total Price',
                        data: [],
                        borderColor: '#f2711c',
                        backgroundColor: 'rgba(242, 113, 28, 0.1)',
                        fill: true,
                        tension: 0.3
                    }]
                },
                options: {
                    responsive: true,
                    scales: {
                        x: { grid: { display: false } },
                        y: {
                            beginAtZero: true,
                            grid: { color: gridColor },
                            ticks: {
                                callback: function(value) {
                                    if (!currencyInfo) return value;
                                    const symbol = currencyInfo.getAttribute('data-symbol');
                                    return symbol + value.toLocaleString();
                                }
                            }
                        }
                    },
                    plugins: {
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    if (!currencyInfo) return context.dataset.label + ': ' + context.parsed.y;
                                    const symbol = currencyInfo.getAttribute('data-symbol');
                                    return context.dataset.label + ': ' + symbol + context.parsed.y.toLocaleString(undefined, {minimumFractionDigits: 2});
                                }
                            }
                        }
                    }
                }
            });

            updatePriceChart();
        });
    </script>
{% endblock %}